### ISSUE TITLE
Support for osx 10.10

### ISSUE THREAD

**Issue by ifuchs** [toy/tms#1]
Has anyone made TMS work on Yosemite (v10.10)?

**Comment by toy** [comment]
I can try to find time to check it at another computer with v10.10.
Could you please describe what is not working? Not installing, not running at all or only certain parts?

**Comment by ifuchs** [comment]
It returns with:

unsupported OSX version - this is BETA software - check for a new release

**Comment by toy** [comment]
That is a strange message. The gem itself does not produce this and if I remember correctly it uses only `tmutil` binary which is part of OS itself. Also you did not precise whether you get this message when installing or running the `tms` binary.

**Comment by ifuchs** [comment]
Perhaps, I am running an older version? I just downloaded the .zip file from Github. What is the proper way to install this?

**Comment by toy** [comment]
Master has the latest version 1.7.1. But you can build and install from the repo by running `gem build tms.gemspec && gem install tms-1.7.1.gem`

**Comment by ifuchs** [comment]
Sorry for the simple minded questions…I did the build and install…how to execute?

**Comment by toy** [comment]
It is installed as if it would get from main gem source, so `tms` if your gem binaries are available in path.

**Comment by ifuchs** [comment]
After doing the build and install, here is what I find :

# locate tms-1.7.1

/Library/Ruby/Gems/2.0.0/cache/tms-1.7.1.gem
/Library/Ruby/Gems/2.0.0/doc/tms-1.7.1
/Library/Ruby/Gems/2.0.0/doc/tms-1.7.1/ri
/Library/Ruby/Gems/2.0.0/doc/tms-1.7.1/ri/cache.ri
/Library/Ruby/Gems/2.0.0/gems/tms-1.7.1
/Library/Ruby/Gems/2.0.0/specifications/tms-1.7.1.gemspec

Executable?

**Comment by toy** [comment]
Should be `/Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/bin/tms`.

**Comment by ifuchs** [comment]
Hmm…

sh-3.2# cd /Users/ihf/Documents/Downloads/tms-master
sh-3.2# gem install tms
Successfully installed tms-1.7.1
Parsing documentation for tms-1.7.1
1 gem installed
sh-3.2# cd /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1
sh-3.2# ls -al
total 0
drwxr-xr-x  2 root  wheel   68 Aug  4 16:29 .
drwxr-xr-x  9 root  wheel  306 Aug  4 16:29 ..

Where’d it go?

**Comment by toy** [comment]
Just a note that when you run `gem install tms` — you install gem from remote (rubygems.org by default).

Can you try to install any other gem, preferably one that is not yet installed (or uninstall it before proceeding), like `rspec`, and check if it is installed correctly?

**Comment by ifuchs** [comment]
Well…

h-3.2# gem install rspec
Fetching: rspec-support-3.3.0.gem (100%)
Successfully installed rspec-support-3.3.0
Fetching: rspec-core-3.3.2.gem (100%)
Successfully installed rspec-core-3.3.2
Fetching: diff-lcs-1.2.5.gem (100%)
Successfully installed diff-lcs-1.2.5
Fetching: rspec-expectations-3.3.1.gem (100%)
Successfully installed rspec-expectations-3.3.1
Fetching: rspec-mocks-3.3.2.gem (100%)
Successfully installed rspec-mocks-3.3.2
Fetching: rspec-3.3.0.gem (100%)
Successfully installed rspec-3.3.0
Parsing documentation for rspec-support-3.3.0
Installing ri documentation for rspec-support-3.3.0
Parsing documentation for rspec-core-3.3.2
Installing ri documentation for rspec-core-3.3.2
Parsing documentation for diff-lcs-1.2.5
Installing ri documentation for diff-lcs-1.2.5
Parsing documentation for rspec-expectations-3.3.1
Installing ri documentation for rspec-expectations-3.3.1
Parsing documentation for rspec-mocks-3.3.2
Installing ri documentation for rspec-mocks-3.3.2
Parsing documentation for rspec-3.3.0
Installing ri documentation for rspec-3.3.0
6 gems installed
sh-3.2# locate gems|grep rspec

(nothing found)

**Comment by toy** [comment]
`locate` will not help you with files that were just created, its database is updated periodically — [man locate](https://developer.apple.com/library/prerelease/mac/documentation/Darwin/Reference/ManPages/man1/locate.1.html).

To check if it was properly installed you can run `gem which rspec` to get the path of `lib/rspec.rb` and check other files by listing contents of path preceding `lib/rspec.rb`.

**Comment by ifuchs** [comment]
Actually, I thought of that and ran locate.updatedb before running that command.

gem which rspec
/Library/Ruby/Gems/2.0.0/gems/rspec-3.3.0/lib/rspec.rb
sh-3.2# gem which tms
ERROR:  Can't find ruby library file or shared library tms
sh-3.2# cd /Library/Ruby/Gems/2.0.0/gems/
sh-3.2# ls
colored-1.2         ffi-xattr-0.0.5         rspec-3.3.0         rspec-mocks-3.3.2       tms-1.7.1
diff-lcs-1.2.5          rake-0.9.6          rspec-core-3.3.2        rspec-support-3.3.0
ffi-1.9.10          rdoc-4.0.0          rspec-expectations-3.3.1    test-unit-2.0.0.0
sh-3.2# cd tms-1.7.1/
sh-3.2# ls

(NULL)

I never use Ruby so I am at sea when it comes to where it puts things.

**Comment by toy** [comment]
Maybe it is easier if I try installing tms on 10.10 and see if there is something wrong, I'll try to do it tomorrow.
You can also try to uninstall tms, check if its directory is removed and install it once more. Will there be any warning/error messages? Will it be empty again?
Also what is the output of `which tms` and `cat $(which tms)`?

**Comment by ifuchs** [comment]
I uninstalled and reinstalled and bingo, the directory is now populated. /usr/bin/tms runs. I have no idea why it didn’t work before.  Thanks much for your help and patience.

**Comment by toy** [comment]
Great! And it means that it works on 10.10.

Can I close the ticket than?

**Comment by ifuchs** [comment]
Yes. Thanks again!

**Comment by ifuchs** [comment]
I got around to running tms against an actual ™ backup and there does seem to be a problem:

Ira-Fuchs-Computer:~ ihf$ tms 2
Using tmutil to detect and mount Time Machine volume
Detected: /Volumes/Untitled/Backups.backupdb/Ira Fuchsâ Computer
Comparing:
1 /Volumes/Untitled/Backups.backupdb/Computer/2015-05-10-122856
2 /Volumes/Untitled/Backups.backupdb/Computer/2015-05-17-000501
ââ â        //
ââ â  10.0K /.DS_Store
  â        /.DocumentRevisions-V100/
  â   1.6K /.OSInstallerMessages
  â   959B /.com.apple.backupd.mvlist.plist
??? !!!!!! /.file
ââ â        /.vol/
ââ â        /Applications/
ââ â  66.0K /Applications/.DS_Store
ââ â        /Applications/.localized
/Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/path.rb:10:in `join': incompatible character encodings: US-ASCII and ASCII-8BIT (Encoding::CompatibilityError)
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/path.rb:10:in`initialize'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/path.rb:14:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/path.rb:14:in`/'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:58:in `block in compare'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:57:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:57:in `compare'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:58:in`block in compare'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:57:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:57:in`compare'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:26:in `block in run'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:24:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms/comparison.rb:24:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/lib/tms.rb:71:in`diff'
    from /Library/Ruby/Gems/2.0.0/gems/tms-1.7.1/bin/tms:100:in `<top (required)>'
    from /usr/bin/tms:23:in`load'
    from /usr/bin/tms:23:in `<main>'

**Comment by toy** [comment]
Do you see «ââ â» as is in terminal or like «█≠█»?

I hope I will be able to check this properly this or next week.

**Comment by ifuchs** [comment]
I see ââ â

**Comment by toy** [comment]
Could you check the output of command `locale` in your terminal?

**Comment by ifuchs** [comment]
$ locale
LANG="en_US.US-ASCII"
LC_COLLATE="en_US.US-ASCII"
LC_CTYPE="en_US.US-ASCII"
LC_MESSAGES="en_US.US-ASCII"
LC_MONETARY="en_US.US-ASCII"
LC_NUMERIC="en_US.US-ASCII"
LC_TIME="en_US.US-ASCII"
LC_ALL=

**Comment by toy** [comment]
Please check the version 1.7.2
